/**
 * @readonly
 * @enum {string}
 */
export const ROLES = {
  CUSTOMER_PANEL: 'PDC',
  NEW_TRANSACTION: 'NTR',
  VEHICLE_DEBITS: 'DVC',
  LOANS: 'EMP',
  FINANCING: 'FCM',
  CADASTRAL_DATA: 'MDC',
  SCHEDULE: 'AGD',
  EXTRACT: 'EXT',
  CONCILIATION: 'CLC',
  TRANSACTION_HISTORY: 'HTR',
  PAYMENT_REPORTS: 'RPG',
  REQUESTS: 'SOL',
  USER_MANAGEMENT: 'GUS'
}
