export default () => ({
  typesOfservices: [],
  valueTotal: [],
  transactionTypes: [],
  fields: [],
  coefficients: [],
  retornoAtivo: 0,
  filteredList: [],
  transactionType: false,
  simulationInstalment: [],
  selectInstalment: [],
  cardBrands: [],
  typeOfservice: "",
  financeService: [],
  listaRetornos: [],
  dadosVariaveis: [],
  transactionObj: [],
  respostaText: [],
  respostaCode: [],
  criouSimulacao: [],
  selectedCard: [],
  btConcluirTransacao: [],
  openTransaction: [],
  formdata2: [],
  requiredFieldKeys: [],
  transactionTypesGroupByFee: []
});
