export default () => ({
  estado: [],
  cpfCnpj: [],
  fee: [],
  placa: [],
  renavan: [],
  email: [],
  debits: [],
  boletos: [],
  operation: [],
  serviceId: "",
  serviceName: "",
  totalDebits: [],
  filters: [],
  generalData: {},
  transaction: [],
  typeTransaction: [],
  installment: [],
  retorno: [],
  time: [],
  requiredFields: [],
  activePaymentDetran: [],
  statusBusca: [],
});
